ASSUME CS:CODE,DS:DATA

DATA SEGMENT
SOURCEADDRESS EQU 2000H
DESTADDRESS EQU 3000H
COUNT EQU 0AH
DATA ENDS

CODE SEGMENT

START: MOV AX,DATA
       MOV DS,AX
       MOV ES,AX
       MOV CX,COUNT
       MOV AX,3030H
       MOV SI, SOURCEADDRESS
BACK:  MOV [SI],AX
       INC AL
       INC AH
       ADD SI,2
       LOOP BACK
       MOV [SI],'$'
       MOV [SI+1],'$'
       MOV SI,SOURCEADDRESS
       MOV DI,DESTADDRESS
       MOV CX,COUNT+1
       CLD
   REP MOVSW

       MOV AH,09H
       MOV DX, DESTADDRESS
       INT 21H

       MOV AH,4CH
       INT 21H
CODE ENDS
END START
